#server:
#  port: 80
#  ssl:
#    enabled: true  # SSL 활성화
#    key-store: classpath:keystore.p12  # 키 저장소 파일 경로
#    key-store-password: Dongcci92!!  # 키 저장소의 비밀번호
#    key-store-type: PKCS12  # 키 저장소 유형
#    key-alias: dong  # 키 별칭

server:
  port: 8080
#  ssl:
#    enabled: true  # SSL 활성화
#    key-store: file:/etc/apache2/ssl/keystore.p12  # 키 저장소 파일 경로
#    key-store-password: Dongcci92!!  # 키 저장소의 비밀번호
#    key-store-type: PKCS12  # 키 저장소 유형
#    key-alias: proxy  # 키 별칭
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssda
#    username: root
#    password: Dongcci92!!

#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://118.67.131.103:3306/ssda
#    username: root
#    password: dongcci

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

servlet:
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 100MB

itemImgLocation: /Users/proxy/items/item/
uploadPath: file:/Users/proxy/items/

jwt:
  secret-key: GaXmsBiD6L1Z2M3NorAExZp8gr3uPXDR6J6iZxe4pfYKTf0SV1+I0xGqmuPG+nmLVCl9/2+lYB/VFI+AgoFGpg==

oauth:
  kakao:
    client-id: 992ac8b159b158f4299b493df0509202
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

